name: Build and Push Docker Image to ghcr.io

on: 
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      imagename:
        required: true
        type: string
      platforms:
        required: true
        type: string
      push:
        required: true
        type: boolean

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        # first step is necessary because image names must be lowercase
      - name: set lower case image name
        run: |
          echo "IMAGE_NAME=${{ inputs.imagename }}" >>${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      # Add tags to metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: latest=true

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=oci,dest=/tmp/image.tar
      - name: Push image with containerd
        if: ${{ inputs.push }}
        run: |
          sudo ctr i import --base-name ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --digests --all-platforms /tmp/image.tar
          while IFS= read -r line; do
            echo "Pushing $line"
            for i in {1..5}; do 
              sudo ctr i push --user "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" $line && break || sleep 15;
            done
          done <<< "${{ steps.meta.outputs.tags }}"
