name: CI

on:
  push:
    branches: [ '*' ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint pylint-exit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 and pylint
      run: |
        flake8 .
        pylint EmbyAniSync.py TautulliSyncHelper.py embymodule.py anilist.py custom_mappings.py || pylint-exit --error-fail --warn-fail $?
  build-docker-embyanisync:
    needs: lint
    uses: rickdb/embyanisync/.github/workflows/build-docker-image.yml@master
    with:
      dockerfile: ./Docker/EmbyAniSync/Dockerfile
      imagename: ${{ github.repository_owner }}/embyanisync
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          
  build-docker-tautulli:
    needs: lint
    uses: rickdb/embyanisync/.github/workflows/build-docker-image.yml@master
    with:
      dockerfile: ./Docker/Tautulli/Dockerfile
      imagename: ${{ github.repository_owner }}/tautulli-embyanisync
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
